### ISSUE TITLE
Import system issue (JSON)

### ISSUE THREAD

**Issue by Ginger143** [StaffsUniGames/Blockout2#119]
after importing sponge on the level is being swapped with the red wall

**Comment by ArnavMehta3000** [comment]
Taking a look at it

**Comment by ArnavMehta3000** [comment]
Fixed exporting directory bug by removing custom user di.

![image](https://github.com/StaffsUniGames/Blockout2/assets/77837038/6e677e3f-007d-4e20-b397-4a9b1c31244a)

**Comment by ArnavMehta3000** [comment]
Unstuck block does not get converted to wall. The spawned object is still the unstuck block, but with a wrong mesh. This will be reviewed after the new meshes are imported

Reason for mesh swapping (issue) still unknown

**Comment by ArnavMehta3000** [comment]
Closing until new meshes are recieved
