### ISSUE TITLE
Space button 

### ISSUE THREAD

**Issue by Ginger143** [StaffsUniGames/Blockout2#50]
After pressing space player is being transferred to the the start point . If player pressed space text to the obstacle (ex wall) its being moved to the start and player can not move.
![UnrealEditor_S6pAgyaXS9](https://github.com/StaffsUniGames/Blockout2/assets/64151392/c204cc7c-8752-4563-9b40-28d04191414a)

**Comment by Ginger143** [comment]
https://github.com/StaffsUniGames/Blockout2/assets/64151392/c08a3019-ca40-4a6e-9aca-fac1d242c721

also after placing the goal sometimes its being triggered and open the "You won " widget

**Comment by ArnavMehta3000** [comment]
Fixed. Closing
